#inicio=int(input("inserte número de inicio: "))
#fin=int(input("inserte número de fin: "))
#buscado=int(input("número buscado: "))
#r=list(range(inicio,fin))
r=list(range(1,21))
print(r)
#print(dir(r))
#print(r[2])
#print(buscado in r)
r.insert(1,0)
print(r)
r.remove(8)
print(r)
r.sort()
print(r)
r.sort(reverse=True)
print(r)
print(r.index(0))